version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: vielheit
      POSTGRES_USER: vielheit
    ports:
      - "5432:5432"
      
  vielheit:
    build: .
    links:
      - postgres
    ports:
      - "8080:3000"
