# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER: vielheit
        - POSTGRES_PASSWORD: vielheit
        - POSTGRES_DB: vielheit_test
   
    working_directory: ~/build

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test
      - run: lein uberjar
      - save_cache:
          paths:
            - ~/build/target/uberjar/vielheit.jar
          key: vielheit.jar-{{ .BuildNum }}

  cljs-test:
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
       
    working_directory: ~/build

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "project.clj" }}
            - npm-
      - run: npm install karma karma-firefox-launcher karma-cljs-test karma-cli
      - restore_cache:
          keys:
          - npm-{{ checksum "project.clj" }}
          - npm-
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein with-profile test doo firefox once

  deploy:
    machine: true
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: no

    working_directory: ~/build
            
    steps:
      - checkout
      - restore_cache:
          keys:
          - vielheit.jar-{{ .BuildNum }}
      - run: pip install ansible
      - run: git clone git@github.com:jmcelwain/hosts.git
      - run: pushd ./hosts; git checkout f971d51; popd 
      - run: cat ./hosts/config >> ~/.ssh/config
      - run: ansible-playbook ./.ansible/site.yml -i ./.ansible/hosts -e "jar_file=$PWD/target/uberjar/vielheit.jar"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - cljs-test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - cljs-test
          filters:
            branches:
              only: feature/2
