---
- name: Provision a new server.

  hosts: vh

  become: true

  vars:
    username: deploy 
    password: $16ZKhkCE8JUk
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  roles:
    # - common
    # - packages
    # - ssh
    # - iptables
    - fail2ban
